extends:
  - next/core-web-vitals
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
ignorePatterns:
  - components/ui/*.tsx
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  quotes:
    - error
    - double
    - avoidEscape: true
  semi:
    - error
    - always
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "[iI]gnored"
      argsIgnorePattern: "[iI]gnored"
      caughtErrorsIgnorePattern: "[iI]gnored"
