name: Format

on:
  push:
    branches:
      - "**"
      -
jobs:
  formatting:
    name: Code Formatting
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:format
